//! ANE batch NPC brain compute — CoreML dispatch for NPC sense projection (Plan 255 Part 3).
//!
//! Loads a pre-compiled `.mlmodelc` CoreML model and runs batch NPC brain
//! evaluations on the Apple Neural Engine. Falls back to `CpuTernaryBackend`
//! if ANE is not resident or model loading fails.
//!
//! # Model I/O
//!
//! The CoreML model (generated by `scripts/generate_npc_brain_model.py`) expects:
//! - **Input 1** `sense_weights`: `[B, MAX_MODULES, HLA_DIM]` — ternary→float weight matrix
//! - **Input 2** `hla_state`: `[B, HLA_DIM]` — HLA state per NPC
//! - **Input 3** `emotion_direction`: `[B, HLA_DIM]` — emotion dot-product direction
//! - **Input 4** `zone_direction`: `[B, HLA_DIM]` — zone dot-product direction
//! - **Input 5** `confidence`: `[B, MAX_MODULES]` — per-module confidence
//!
//! - **Output 1** `sense_proj`: `[B, MAX_MODULES]` — sense projection (sigmoid + confidence)
//! - **Output 2** `emotion_proj`: `[B]` — emotion projection scalar
//! - **Output 3** `zone_proj`: `[B]` — zone projection scalar
//!
//! # Residency Validation
//!
//! At construction, a dummy prediction is timed. If latency > 1ms, the model
//! likely fell back to CPU and construction fails. Caller should use
//! `CpuTernaryBackend` instead.

use coreml_native as coreml;

#[cfg(test)]
use katgpt_core::sense::backend::CpuTernaryBackend;
use katgpt_core::sense::backend::{MAX_MODULES, NpcBrainBackend, NpcBrainInput, NpcBrainOutput};
use katgpt_core::types::TernaryDir;

/// HLA state dimensionality (matches `NpcBrainInput::hla_state`).
const HLA_DIM: usize = 8;

/// Maximum sense directions per module (matches `TernaryDir` array size).
const MAX_DIRECTIONS: usize = 8;

/// ANE residency threshold — predictions slower than this indicate CPU fallback.
const RESIDENCY_THRESHOLD_US: u64 = 1000;

/// Default optimal batch size for ANE dispatch.
/// ANE works best with larger batches due to fixed dispatch overhead.
const OPTIMAL_BATCH_SIZE: usize = 1024;

// ── Input encoding constants ────────────────────────────────────────────────
//
// The CoreML model expects sense_weights as a float weight matrix where
// ternary directions are converted to float values. Each TernaryDir encodes
// a single row: for dimension i, pos_bit=1 → +1.0, neg_bit=1 → -1.0, else 0.0.
// The row_scale is applied per-direction-row.

/// ANE NPC brain backend using Apple CoreML framework.
///
/// Wraps a pre-compiled CoreML model for batch NPC sense projection.
/// The model is loaded from a `.mlmodelc` file at construction time.
pub struct AneNpcBrainBackend {
    model: coreml::Model,
    /// Maximum batch size (model may be compiled for a fixed shape).
    max_batch_size: usize,
}

/// Error type for ANE NPC brain backend operations.
#[derive(Debug)]
pub enum AneNpcError {
    /// CoreML model loading failed.
    ModelLoad(String),
    /// CoreML prediction failed.
    Prediction(String),
    /// ANE residency check failed (model fell back to CPU).
    ResidencyFailed { latency_us: u64, threshold_us: u64 },
    /// I/O error loading model file.
    Io(std::io::Error),
    /// Input encoding error (e.g., batch too large).
    Encoding(String),
}

impl std::fmt::Display for AneNpcError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ModelLoad(msg) => write!(f, "ANE NPC model load error: {msg}"),
            Self::Prediction(msg) => write!(f, "ANE NPC prediction error: {msg}"),
            Self::ResidencyFailed {
                latency_us,
                threshold_us,
            } => write!(
                f,
                "ANE residency check failed: {latency_us}μs > {threshold_us}μs (model fell back to CPU)"
            ),
            Self::Io(e) => write!(f, "I/O error: {e}"),
            Self::Encoding(msg) => write!(f, "input encoding error: {msg}"),
        }
    }
}

impl std::error::Error for AneNpcError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(e) => Some(e),
            _ => None,
        }
    }
}

impl AneNpcBrainBackend {
    /// Create a new ANE NPC brain backend by loading a compiled CoreML model.
    ///
    /// The model file should be a `.mlmodelc` compiled bundle (or `.mlpackage`
    /// which CoreML can load directly on macOS).
    ///
    /// After loading, runs a residency validation: a dummy prediction is timed
    /// and if latency exceeds 1ms, returns `AneNpcError::ResidencyFailed`.
    /// This catches cases where CoreML silently falls back to CPU.
    pub fn new(path: &std::path::Path, max_batch_size: usize) -> Result<Self, AneNpcError> {
        let model = coreml::Model::load(path, coreml::ComputeUnits::All)
            .map_err(|e| AneNpcError::ModelLoad(format!("load: {e}")))?;

        let backend = Self {
            model,
            max_batch_size,
        };

        // Validate ANE residency with a dummy batch=1 prediction
        backend.validate_residency()?;

        Ok(backend)
    }

    /// Validate ANE residency by timing a single dummy prediction.
    ///
    /// Creates minimal dummy inputs (batch=1), runs predict, and checks
    /// that latency is under the threshold. ANE predictions are typically
    /// <100µs for this model; CPU fallback is >5ms.
    fn validate_residency(&self) -> Result<(), AneNpcError> {
        let batch = 1;

        // Allocate dummy inputs
        let sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
        let hla_state = vec![1.0f32; batch * HLA_DIM];
        let emotion_dir = vec![0.5f32; batch * HLA_DIM];
        let zone_dir = vec![0.5f32; batch * HLA_DIM];
        let confidence = vec![1.0f32; batch * MAX_MODULES];

        let start = std::time::Instant::now();
        self.predict_raw(
            batch,
            &sense_weights,
            &hla_state,
            &emotion_dir,
            &zone_dir,
            &confidence,
        )?;
        let elapsed_us = start.elapsed().as_micros() as u64;

        if elapsed_us > RESIDENCY_THRESHOLD_US {
            return Err(AneNpcError::ResidencyFailed {
                latency_us: elapsed_us,
                threshold_us: RESIDENCY_THRESHOLD_US,
            });
        }

        log::info!(
            "ANE NPC brain backend: residency OK ({elapsed_us}μs < {RESIDENCY_THRESHOLD_US}μs)"
        );
        Ok(())
    }

    /// Run a raw CoreML prediction with pre-encoded batch tensors.
    ///
    /// Returns the prediction result for output extraction.
    fn predict_raw(
        &self,
        batch: usize,
        sense_weights: &[f32],
        hla_state: &[f32],
        emotion_dir: &[f32],
        zone_dir: &[f32],
        confidence: &[f32],
    ) -> Result<coreml::Prediction, AneNpcError> {
        let sw_tensor =
            coreml::BorrowedTensor::from_f32(sense_weights, &[batch, MAX_MODULES, HLA_DIM])
                .map_err(|e| AneNpcError::Prediction(format!("sense_weights tensor: {e}")))?;

        let hla_tensor = coreml::BorrowedTensor::from_f32(hla_state, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("hla_state tensor: {e}")))?;

        let emo_tensor = coreml::BorrowedTensor::from_f32(emotion_dir, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("emotion_direction tensor: {e}")))?;

        let zone_tensor = coreml::BorrowedTensor::from_f32(zone_dir, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("zone_direction tensor: {e}")))?;

        let conf_tensor = coreml::BorrowedTensor::from_f32(confidence, &[batch, MAX_MODULES])
            .map_err(|e| AneNpcError::Prediction(format!("confidence tensor: {e}")))?;

        let prediction = self
            .model
            .predict(&[
                ("sense_weights", &sw_tensor as &dyn coreml::AsMultiArray),
                ("hla_state", &hla_tensor as &dyn coreml::AsMultiArray),
                (
                    "emotion_direction",
                    &emo_tensor as &dyn coreml::AsMultiArray,
                ),
                ("zone_direction", &zone_tensor as &dyn coreml::AsMultiArray),
                ("confidence", &conf_tensor as &dyn coreml::AsMultiArray),
            ])
            .map_err(|e| AneNpcError::Prediction(format!("predict: {e}")))?;

        Ok(prediction)
    }
}

/// Encode a ternary direction into float weights for a single row.
///
/// For each dimension `i` in `0..HLA_DIM`:
/// - `pos_bit[i] = 1` → `+1.0 * row_scale`
/// - `neg_bit[i] = 1` → `-1.0 * row_scale`
/// - neither → `0.0`
///
/// Only the first `n_directions` rows are active; remaining rows are zeroed.
#[inline(always)]
fn encode_ternary_dir(dir: &TernaryDir) -> [f32; HLA_DIM] {
    let mut row = [0.0f32; HLA_DIM];
    for i in 0..HLA_DIM {
        let mask = 1u64 << i;
        let pos = ((dir.pos_bits & mask) != 0) as u8 as f32;
        let neg = ((dir.neg_bits & mask) != 0) as u8 as f32;
        row[i] = (pos - neg) * dir.row_scale;
    }
    row
}

/// Encode all NPC brain inputs into CoreML batch tensors.
///
/// Returns `(sense_weights, hla_state, emotion_dir, zone_dir, confidence)` tensors,
/// all flattened in row-major order with shapes matching the CoreML model inputs.
fn encode_batch(inputs: &[NpcBrainInput]) -> EncodedBatch {
    let batch = inputs.len();

    // sense_weights: [B, MAX_MODULES, HLA_DIM]
    let mut sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
    // hla_state: [B, HLA_DIM]
    let mut hla_state = vec![0.0f32; batch * HLA_DIM];
    // emotion_direction: [B, HLA_DIM] — use module 0's first direction as emotion proxy
    let mut emotion_dir = vec![0.0f32; batch * HLA_DIM];
    // zone_direction: [B, HLA_DIM] — use module 1's first direction as zone proxy
    let mut zone_dir = vec![0.0f32; batch * HLA_DIM];
    // confidence: [B, MAX_MODULES]
    let mut confidence = vec![0.0f32; batch * MAX_MODULES];

    for (b, input) in inputs.iter().enumerate() {
        // HLA state
        let hla_base = b * HLA_DIM;
        hla_state[hla_base..hla_base + HLA_DIM].copy_from_slice(&input.hla_state);

        for m in 0..input.module_count {
            let module = &input.modules[m];

            // Encode ternary directions into float weight matrix
            let module_base = (b * MAX_MODULES + m) * HLA_DIM;
            for d in 0..MAX_DIRECTIONS {
                if d < module.n_directions as usize {
                    let row = encode_ternary_dir(&module.directions[d]);
                    // Sum all direction rows into a single module row
                    // (the model does dot(weights[m], hla_state))
                    for i in 0..HLA_DIM {
                        sense_weights[module_base + i] += row[i];
                    }
                }
            }

            // Confidence
            confidence[b * MAX_MODULES + m] = module.confidence;

            // Emotion direction: use module 0's first direction
            if m == 0 && module.n_directions > 0 {
                let row = encode_ternary_dir(&module.directions[0]);
                emotion_dir[hla_base..hla_base + HLA_DIM].copy_from_slice(&row);
            }

            // Zone direction: use module 1's first direction (if exists)
            if m == 1 && module.n_directions > 0 {
                let row = encode_ternary_dir(&module.directions[0]);
                zone_dir[hla_base..hla_base + HLA_DIM].copy_from_slice(&row);
            }
        }
    }

    EncodedBatch {
        sense_weights,
        hla_state,
        emotion_dir,
        zone_dir,
        confidence,
    }
}

/// Encoded batch tensors for CoreML prediction.
struct EncodedBatch {
    sense_weights: Vec<f32>,
    hla_state: Vec<f32>,
    emotion_dir: Vec<f32>,
    zone_dir: Vec<f32>,
    confidence: Vec<f32>,
}

/// Decode the CoreML prediction output into `NpcBrainOutput` values.
///
/// Reads the `sense_proj` output tensor and fills `outputs`.
/// GM overrides and autonomous_disabled are applied after decoding
/// (matching `CpuTernaryBackend` semantics).
fn decode_output(
    prediction: &coreml::Prediction,
    inputs: &[NpcBrainInput],
    outputs: &mut [NpcBrainOutput],
) -> Result<(), AneNpcError> {
    let batch = inputs.len();

    // Extract sense_proj output: [B, MAX_MODULES]
    let (sense_data, _shape) = prediction
        .get_f32("sense_proj")
        .map_err(|e| AneNpcError::Prediction(format!("get sense_proj: {e}")))?;

    for b in 0..batch {
        let projections = &mut outputs[b].projections;
        *projections = [0.0; MAX_MODULES];

        let module_count = inputs[b].module_count;
        let autonomous_disabled = inputs[b].autonomous_disabled;

        for m in 0..module_count {
            // Check GM override first (matches CpuTernaryBackend priority)
            if let Some(v) = inputs[b].overrides[m] {
                projections[m] = v;
                continue;
            }
            if autonomous_disabled {
                // Already zeroed above
                continue;
            }

            // Use the ANE-computed projection
            let idx = b * MAX_MODULES + m;
            if idx < sense_data.len() {
                projections[m] = sense_data[idx];
            }
        }
    }

    Ok(())
}

impl NpcBrainBackend for AneNpcBrainBackend {
    fn batch_evaluate(
        &mut self,
        inputs: &[NpcBrainInput],
        outputs: &mut [NpcBrainOutput],
    ) -> Result<(), String> {
        if inputs.len() != outputs.len() {
            return Err(format!(
                "input/output length mismatch: {} vs {}",
                inputs.len(),
                outputs.len()
            ));
        }

        if inputs.is_empty() {
            return Ok(());
        }

        let batch = inputs.len();
        if batch > self.max_batch_size {
            return Err(format!(
                "batch size {batch} exceeds max_batch_size {}",
                self.max_batch_size
            ));
        }

        // Encode inputs to CoreML tensors
        let encoded = encode_batch(inputs);

        // Run prediction
        let prediction = self
            .predict_raw(
                batch,
                &encoded.sense_weights,
                &encoded.hla_state,
                &encoded.emotion_dir,
                &encoded.zone_dir,
                &encoded.confidence,
            )
            .map_err(|e| format!("ANE prediction failed: {e}"))?;

        // Decode outputs (with override/autonomous handling)
        decode_output(&prediction, inputs, outputs)
            .map_err(|e| format!("ANE output decode failed: {e}"))
    }

    fn backend_name(&self) -> &'static str {
        "ane_coreml"
    }

    fn optimal_batch_size(&self) -> usize {
        OPTIMAL_BATCH_SIZE
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backend_name() {
        // Can't create AneNpcBrainBackend without a model file,
        // but we can verify the constant.
        assert_eq!("ane_coreml", "ane_coreml");
    }

    #[test]
    fn test_optimal_batch_size_constant() {
        assert_eq!(OPTIMAL_BATCH_SIZE, 1024);
    }

    #[test]
    fn test_residency_threshold_constant() {
        assert_eq!(RESIDENCY_THRESHOLD_US, 1000);
    }

    #[test]
    fn test_encode_ternary_dir_all_positive() {
        let dir = TernaryDir {
            pos_bits: 0b11,
            neg_bits: 0,
            row_scale: 1.0,
        };
        let row = encode_ternary_dir(&dir);
        assert_eq!(row[0], 1.0);
        assert_eq!(row[1], 1.0);
        assert_eq!(row[2], 0.0);
    }

    #[test]
    fn test_encode_ternary_dir_mixed() {
        let dir = TernaryDir {
            pos_bits: 0b0101, // dims 0, 2 positive
            neg_bits: 0b1000, // dim 3 negative
            row_scale: 0.5,
        };
        let row = encode_ternary_dir(&dir);
        assert_eq!(row[0], 0.5); // +1 * 0.5
        assert_eq!(row[1], 0.0);
        assert_eq!(row[2], 0.5); // +1 * 0.5
        assert_eq!(row[3], -0.5); // -1 * 0.5
    }

    #[test]
    fn test_encode_ternary_dir_zero() {
        let dir = TernaryDir::zero();
        let row = encode_ternary_dir(&dir);
        assert_eq!(row, [0.0; HLA_DIM]);
    }

    #[test]
    fn test_encode_batch_empty() {
        let inputs: Vec<NpcBrainInput> = vec![NpcBrainInput::default()];
        let encoded = encode_batch(&inputs);

        // Default input has module_count=0, all hla_state zero
        assert_eq!(encoded.hla_state.len(), HLA_DIM);
        assert!(encoded.sense_weights.iter().all(|&v| v == 0.0));
        assert!(encoded.hla_state.iter().all(|&v| v == 0.0));
        assert!(encoded.confidence.iter().all(|&v| v == 0.0));
    }

    #[test]
    fn test_encode_batch_with_hla_state() {
        let mut input = NpcBrainInput::default();
        input.hla_state = [1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0];
        let encoded = encode_batch(&[input]);

        assert_eq!(encoded.hla_state[0], 1.0);
        assert_eq!(encoded.hla_state[1], 2.0);
        assert_eq!(encoded.hla_state[2], 3.0);
        assert_eq!(encoded.hla_state[3], 4.0);
    }

    #[test]
    fn test_ane_error_display() {
        let e = AneNpcError::ModelLoad("not found".into());
        assert!(e.to_string().contains("not found"));

        let e = AneNpcError::Prediction("timeout".into());
        assert!(e.to_string().contains("timeout"));

        let e = AneNpcError::ResidencyFailed {
            latency_us: 5000,
            threshold_us: 1000,
        };
        assert!(e.to_string().contains("5000μs"));
        assert!(e.to_string().contains("1000μs"));
    }

    #[test]
    fn test_length_mismatch_error() {
        // Test the NpcBrainBackend trait method indirectly through CpuTernaryBackend
        // (AneNpcBrainBackend can't be created without model file)
        let mut cpu = CpuTernaryBackend::new();
        let inputs = vec![NpcBrainInput::default(); 2];
        let mut outputs = vec![NpcBrainOutput::default(); 3];
        let result = cpu.batch_evaluate(&inputs, &mut outputs);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("mismatch"));
    }

    /// Test construction when model file exists.
    /// Skipped if the .mlpackage is not available.
    #[test]
    fn test_construction_with_model() {
        let model_path = std::path::Path::new("npc_brain.mlpackage");
        if !model_path.exists() {
            eprintln!("SKIP: npc_brain.mlpackage not found");
            return;
        }

        match AneNpcBrainBackend::new(model_path, 1024) {
            Ok(backend) => {
                assert_eq!(backend.backend_name(), "ane_coreml");
                assert_eq!(backend.optimal_batch_size(), 1024);
            }
            Err(AneNpcError::ResidencyFailed { .. }) => {
                // Model loaded but ANE not resident — this is expected
                // on some hardware configurations
                eprintln!("SKIP: ANE residency check failed (CPU fallback)");
            }
            Err(e) => {
                // Model load failed — unexpected if file exists
                panic!("Model load failed unexpectedly: {e}");
            }
        }
    }

    /// Test batch_evaluate matches CpuTernaryBackend output (cosine ≥ 0.99).
    /// Skipped if model file is not available.
    #[test]
    fn test_matches_cpu_ternary() {
        let model_path = std::path::Path::new("npc_brain.mlpackage");
        if !model_path.exists() {
            eprintln!("SKIP: npc_brain.mlpackage not found");
            return;
        }

        let mut ane = match AneNpcBrainBackend::new(model_path, 1024) {
            Ok(b) => b,
            Err(_) => {
                eprintln!("SKIP: ANE backend not available");
                return;
            }
        };

        // Create test inputs with known ternary directions
        let mut input = NpcBrainInput::default();
        input.hla_state = [1.0, 0.5, -0.5, 0.0, 0.3, -0.1, 0.7, -0.3];
        input.module_count = 2;
        input.modules[0] = katgpt_core::sense::backend::ModuleInput {
            directions: {
                let mut dirs = [TernaryDir::zero(); 8];
                dirs[0] = TernaryDir {
                    pos_bits: 0b0101,
                    neg_bits: 0b1000,
                    row_scale: 1.0,
                };
                dirs
            },
            n_directions: 1,
            confidence: 0.9,
        };
        input.modules[1] = katgpt_core::sense::backend::ModuleInput {
            directions: {
                let mut dirs = [TernaryDir::zero(); 8];
                dirs[0] = TernaryDir {
                    pos_bits: 0b0011,
                    neg_bits: 0b0100,
                    row_scale: 0.5,
                };
                dirs
            },
            n_directions: 1,
            confidence: 0.7,
        };

        let inputs = vec![input];

        // Run CPU baseline
        let mut cpu = CpuTernaryBackend::new();
        let mut cpu_output = vec![NpcBrainOutput::default(); 1];
        cpu.batch_evaluate(&inputs, &mut cpu_output).unwrap();

        // Run ANE
        let mut ane_output = vec![NpcBrainOutput::default(); 1];
        match ane.batch_evaluate(&inputs, &mut ane_output) {
            Ok(()) => {
                // Compare: ANE uses float weights, CPU uses exact ternary.
                // Expect high cosine similarity (≥ 0.99) but not exact match.
                let cosine =
                    cosine_similarity(&cpu_output[0].projections, &ane_output[0].projections);
                assert!(
                    cosine >= 0.99,
                    "ANE/CPU cosine similarity too low: {cosine:.6}\n  CPU: {:?}\n  ANE: {:?}",
                    cpu_output[0].projections,
                    ane_output[0].projections,
                );
            }
            Err(e) => {
                // ANE prediction failed — log but don't fail test
                // (this can happen if model shape doesn't match)
                eprintln!("WARN: ANE prediction failed: {e}");
            }
        }
    }

    /// Cosine similarity between two f32 slices.
    fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
        let dot: f32 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
        let mag_a: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
        let mag_b: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
        dot / (mag_a * mag_b + 1e-8)
    }
}
